### ISSUE TITLE
Gillian-JS is broken

### ISSUE THREAD

**Issue by giltho** [GillianPlatform/Gillian#113]
Gillian-JS has been broken by #95, and should be fixed.

**Comment by chrishappy** [comment]
Similar to @NicolasArmero in #208, I am a university student (undergrad) looking for existing frameworks that support JS Symbolic testing (specifically, in TypeScript).

First off, thank you @NatKarmios for your hard work on fixing this issue.

Question: Is there a previous artifact or branch or commit that worked before the breaking change in Gillian-JS?

**Comment by NatKarmios** [comment]
I'm afraid I don't know a particular place where JS was working - these breakages occurred before I began working on the project.

You might find luck using the VM image published with the Gillian Part II paper, found [here](https://zenodo.org/record/4838116), but it's almost 2 years old.
I'm expecting JS to be fixed in the next week or two, so I might suggest holding on a little longer if possible :)

**Comment by giltho** [comment]
Hello!
So JS broke after this PR: https://github.com/GillianPlatform/Gillian/pull/95. Anything before that should have JS working.

The main issue however, is that, as they do, dependences break, because the OCaml ecosystem is the tinsiest bit unstable 🙃 . 
Also, pinging @j3fsantos , I think there is a version of JaVerT still working somewhere, which was used for a PhD thesis about promises etc..

**Comment by chrishappy** [comment]
Yay! Thank you so much @NatKarmios and @giltho!

While we shifted our research project to Concolic testing on Java, I am really excited to perhaps use this project in future projects :)
