### ISSUE TITLE
m4 not found

### ISSUE THREAD

**Issue by bobismijnnaam** [GillianPlatform/Gillian#69]
Following the installation instructions outlined in https://github.com/javert2/JaVerT2.0/issues/1, I get the following error:

```
[nix-shell:/tmp/esy_npm/Gillian]$ ./node_modules/.bin/esy
info esy 0.6.7 (using esy.json)
.... fetching esy-gmp@archive:https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz#sha1:9dc698119                                                                                             .... fetching @opam/z3@archive:https://github.com/Z3Prover/z3/archive/z3-4.8.7.tar.gz#md5:18e                                                                                             info fetching: done
.... installing esy-gmp@archive:https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz#sha1:9dc6981                                                                                             .... installing @opam/z3@archive:https://github.com/Z3Prover/z3/archive/z3-4.8.7.tar.gz#md5:1                                                                                             info installing: done
info building @esy-ocaml/substs@0.0.1@d41d8cd9
info building ocaml@4.10.0@d41d8cd9
info building esy-gmp@archive:https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz#sha1:9dc6981197a7d92f339192eea974f5eca48fcffe@186b9388
info building @esy-ocaml/substs@0.0.1@d41d8cd9: done
info building @opam/conf-perl@opam:1@a6896ba6
info building @opam/conf-python-2-7@opam:1.1@7cada3a6
info building @opam/base-unix@opam:base@87d0b2eb
info building @opam/base-threads@opam:base@36803084
info building @opam/conf-m4@opam:1@3b2b148a
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/conf-m4@opam:1
    # esy-build-package: pwd: /home/bobe/.esy/3/b/opam__s__conf_m4-opam__c__1-75f0454e
    # esy-build-package: running: 'sh' '-exc' 'echo | m4'
    + echo
    + m4
    /usr/bin/sh: 1: m4: not found
    error: command failed: 'sh' '-exc' 'echo | m4' (exited with 127)
    esy-build-package: exiting with errors above...

  building @opam/conf-m4@opam:1
esy: exiting due to errors above

[nix-shell:/tmp/esy_npm/Gillian]$ which m4
/nix/store/rap8fk264z136wqd1rmp7h8y5y8wvdis-gnum4-1.4.18/bin/m4

[nix-shell:/tmp/esy_npm/Gillian]$ sh -exc 'echo | m4'
+ echo
+ m4
```

The only difference is that I installed esy locally (i.e. without the `-g` flag), as I would like to keep any dependencies to the Gillian folder (and, the package manager I use for installing npm, nix, does not support -g it seems). The error surprises me, as the command succeeds if I execute it manually. Maybe esy restricts the PATH too much, or forgets to install m4? I can provide more information if needed.

Is this an internal error or is it mandatory to install esy with `-g`? If that is so I will, but if possible I'd like to be able to run esy/Gillian in a contained manner (although, I've already spotted a pretty big `.esy` folder in `~/.esy`, so it seems this plan has already failed).

**Comment by giltho** [comment]
Hello !

I'm so sorry for looking at this so late. I had muted the github notifications due to a wrong manipulation...

- I don't really know about installing esy locally, it shouldn't really be done I guess ? `esy` is not a dependency of Gillian, it's the packet manager that lets you install the dependencies of Gillian. I think, in any case, the dependencies are going to be written in your `~/.esy/` folder as you noticed. `npm install esy` will just put the esy binary inside your node_modules instead of the your home's node_modules. esy is distributed through npm for convenience but it's just a binary, I think some people wrote a nix derivation for esy if you don't want to install it through npm
- The conf-m4 error is surprising.. I don't see how it could be happening there. Can you try installing with -g and see what happens ? Otherwise that seems like an `esy` bug...

**Comment by bobismijnnaam** [comment]
I did not really look at this more deeply, but the web interfaced worked more or less for me. If I want to do some more testing I'll just bite the bullet and follow your instructions, so I'm closing this if that's okay with you.
